### ISSUE TITLE
Any ERP Detector examples?

### ISSUE THREAD

**Issue by encoded-evolution** [ChrisVeigl/BrainBay#35]
Hi Chris, are there any examples that contain and use ERP-Detector?

**Comment by ChrisVeigl** [comment]
There are 2 examples which use the ERP-element for EMG pattern recognition:

CONFIGURATIONS\EMG\emg_recognition.con
CONFIGURATIONS\EMG\emg_recognition2.con

these examples show the ERP-detector in running state: it outputs the similarity of the current signal to a pre-recorded signal shape. (this makes more sense for e.g EMG patterns or IMU-data than for a free running EEG). 

In order to record a signal shape, a number of samples are averaged and the resulting shape is stored to an .erp file.
see user manual, page 23.

**Comment by encoded-evolution** [comment]
Thanks for this @ChrisVeigl  I will have a look at the examples
